sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t hyemmie/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true hyemmie/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket_name: "elasticbeanstalk-us-east-2-893905995360"
  bucket_path: "docker-react-app"
  on:
    branch: master
